### ISSUE TITLE
Need To Transfer Database To JGetrost.com

### ISSUE THREAD

**Issue by snuss967** [GETHIP-Classroom/get-hip-project-2016-wall#4]
Our Database on JGetrost.com is empty, we need to recreate the tables on James' Server, before Saturday if possible so we can integrate everything then. Can you tackle this Huang as you already know the DB architecture you want? I know we didn't discuss this Saturday.

**Comment by jhuang277** [comment]
Yeah I'll try to get it uploaded tonight, if not by the end of tomorrow.

**Comment by snuss967** [comment]
Awesome

**Comment by jhuang277** [comment]
I'm trying to forward my schema to our database, but I'm getting an access denied error. I emailed Zach and James. Hopefully, we can get it up by tomorrow.

**Comment by jhuang277** [comment]
The schema is updated with tables.

**Comment by snuss967** [comment]
Awesome
