### ISSUE TITLE
Moved Issue #3

### ISSUE THREAD

**Issue by snuss967** [GETHIP-Classroom/get-hip-project-2016-wall#5]
Martin and Gabi, how are you guys sitting? Some of the code that is still lingering in the Pull Request that has never gotten accepted takes care of much of the dynamic nature of the page if you still need it just look in the JavaScript Folders it is heavily commented and has been tested for the most part. Not fully complete because there is a lot of HTML on it that I left out. Don't feel like you have to use it. If you need anything let me know I know that that goes for Taylor too.

**Comment by snuss967** [comment]
Also can we get better at looking at each others code? Many of the changes Jason Pus made yesterday were made in the Pull Request still lingering that has not been updated since Friday night by me and that has never been accepted. Just an Idea.
No offense intended to anyone. Sorry if it reads that way.

**Comment by McHugh-Taylor** [comment]
What would you guy like me to do?

The only thing I have done is the drawn picture of the home page

**Comment by sjaapag319** [comment]
WAll
